version: '3.4'
services:
    webmongoapi:
        container_name: ${DOCKER_REGISTRY-}webmongoapi
        build: 
             context: .
             dockerfile: ./Dockerfile
        environment:
           - ASPNETCORE_ENVIRONMENT=Development 
           - "DatabaseSettings__MongoConnectionString=mongodb://boobsMongo:27017" 
         
    reverse-proxy:
        container_name: reverse-proxy
        image: nginx:1.11.3
        ports:
         - "9090:8080"
        volumes:
         - ./proxy.conf:/etc/nginx/conf.d/default.conf

    boobsmongo:
         image: mongo
         container_name: boobsMongo
         restart: always
         ports:
           - "27017:27017"
